services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${NODE_ENV}
    stdin_open: true
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - APP_URL=${APP_URL}
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

