apiVersion: v1
kind: Service
metadata:
  name: infnet-guia-minikube-service
spec:
  type: NodePort
  selector:
    app: infnet-guia-minikube
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
